### ISSUE TITLE
Newer board revisions missing

### ISSUE THREAD

**Issue by matthijskooijman** [adafruit/Adafruit-Feather-ESP8266-HUZZAH-PCB#2]
This repo contains the design files for revC boards, but I recently bought a board that was revE. Could you make available the newer revisions (preferable also include revD if it was every produced)? Also, the schematic on the [website](https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/downloads) are revC and should probably be updated. Thanks!

**Comment by ladyada** [comment]
oK!

**Comment by matthijskooijman** [comment]
Thanks :-)
