### ISSUE TITLE
Is ground disconnected on the Rev E reset switch? Should it be?

### ISSUE THREAD

**Issue by jadudm** [adafruit/Adafruit-Feather-ESP8266-HUZZAH-PCB#3]
In looking at the Rev E board layout, it is unclear what role the reset switch plays. 

The two reset lines are connected, but it appears that the ground side of the switch is unconnected to anything at all. I've attached a screenshot closeup.

<img width="361" alt="Screen Shot 2019-07-25 at 3 02 21 PM" src="https://user-images.githubusercontent.com/38290/61901285-649cf180-aeed-11e9-924b-71428c0b2443.png">

I also could be misreading the board completely.

**Comment by ladyada** [comment]
theres a ground plane
